import type { Mission } from "./types";

// Eight authored missions. Each introduces one idea: a single well, a robust parcel,
// timing, debris, a second well, a moving well, ricochets and finally everything at once.
// Every `reference` is a real delivery found by scripts/solve.ts and verified in tests.

const BOUNDS = { x: 9.5, y: 6 };

export const MISSIONS: Mission[] = [
  {
    id: "mug",
    title: "A Mug for the Moon Café",
    client: "The Moon Café",
    item: "One (1) mug",
    parcel: "fragile",
    note: "The moon is pulling. Follow the curve, not your instincts.",
    depot: { x: -7, y: -2 },
    bodies: [
      {
        id: "moon",
        name: "Minor Moon",
        radius: 0.8,
        gm: 7,
        motion: { kind: "fixed", at: { x: 1.5, y: 0 } },
        look: "moon",
      },
    ],
    obstacles: [],
    dock: {
      name: "Moon Café",
      motion: { kind: "orbit", around: "moon", radius: 1.7, omega: 0.45, phase: 2.6 },
      captureRadius: 0.42,
    },
    guideSeconds: 4,
    maxFlightSeconds: 8,
    fuelPar: 45,
    bounds: BOUNDS,
    reference: { delayTicks: 300, aim: { angle: 359, power: 20 }, brakeStep: 288 },
  },
  {
    id: "paperwork",
    title: "Paperwork, Regrettably",
    client: "Grudge Planetary Records",
    item: "Brick of paperwork",
    parcel: "robust",
    note: "Paperwork is robust. So is the customer's disappointment.",
    depot: { x: -7.5, y: 2.5 },
    bodies: [
      {
        id: "grudge",
        name: "Grudge",
        radius: 1,
        gm: 9,
        motion: { kind: "fixed", at: { x: 1, y: 0.5 } },
        look: "rust",
      },
    ],
    obstacles: [],
    dock: {
      name: "Records Office",
      motion: { kind: "orbit", around: "grudge", radius: 2, omega: -0.35, phase: 3.2 },
      captureRadius: 0.42,
    },
    guideSeconds: 4,
    maxFlightSeconds: 8,
    fuelPar: 30,
    bounds: BOUNDS,
    reference: { delayTicks: 270, aim: { angle: 9, power: 45 }, brakeStep: 60 },
  },
  {
    id: "teapot",
    title: "Express Is a State of Mind",
    client: "Orbital Tea Rooms",
    item: "Teapot",
    parcel: "fragile",
    note: "The tea rooms orbit faster on weekdays. Launch on time, or at least nearby.",
    depot: { x: -7.5, y: 0 },
    bodies: [
      {
        id: "pip",
        name: "Pip",
        radius: 0.7,
        gm: 6,
        motion: { kind: "fixed", at: { x: 2, y: -0.5 } },
        look: "ice",
      },
    ],
    obstacles: [],
    dock: {
      name: "Tea Rooms",
      motion: { kind: "orbit", around: "pip", radius: 1.5, omega: 0.9, phase: 0 },
      captureRadius: 0.4,
    },
    guideSeconds: 3.5,
    maxFlightSeconds: 8,
    fuelPar: 45,
    bounds: BOUNDS,
    reference: { delayTicks: 330, aim: { angle: 341, power: 25 }, brakeStep: 300 },
  },
  {
    id: "vase",
    title: "Mind the Debris",
    client: "A Grandmother, Unnamed",
    item: "Heirloom vase",
    parcel: "fragile",
    note: "Debris is not our responsibility. Neither, legally, is the vase.",
    depot: { x: -7.5, y: 0 },
    bodies: [
      {
        id: "nana",
        name: "Nana's Moon",
        radius: 0.9,
        gm: 8,
        motion: { kind: "fixed", at: { x: 3, y: 0 } },
        look: "moon",
      },
    ],
    obstacles: [
      { id: "d1", radius: 0.5, motion: { kind: "fixed", at: { x: -3.2, y: 0 } } },
      { id: "d2", radius: 0.45, motion: { kind: "fixed", at: { x: -2.2, y: 1.6 } } },
      { id: "d3", radius: 0.45, motion: { kind: "fixed", at: { x: -2.4, y: -1.6 } } },
    ],
    dock: {
      name: "Nana's Porch",
      motion: { kind: "orbit", around: "nana", radius: 1.8, omega: 0.4, phase: 4 },
      captureRadius: 0.42,
    },
    guideSeconds: 4,
    maxFlightSeconds: 8,
    fuelPar: 50,
    bounds: BOUNDS,
    reference: { delayTicks: 150, aim: { angle: 350, power: 40 }, brakeStep: 312 },
  },
  {
    id: "opinions",
    title: "Two Masters",
    client: "Petty Customs & Excise",
    item: "Crate of opinions",
    parcel: "robust",
    note: "Two gravity wells. Management calls this synergy.",
    depot: { x: -7.5, y: -3 },
    bodies: [
      {
        id: "bent",
        name: "Big Bent",
        radius: 1.2,
        gm: 12,
        motion: { kind: "fixed", at: { x: -1, y: 2.5 } },
        look: "gas",
      },
      {
        id: "petty",
        name: "Petty",
        radius: 0.6,
        gm: 4,
        motion: { kind: "fixed", at: { x: 4, y: -1.5 } },
        look: "ice",
      },
    ],
    obstacles: [],
    dock: {
      name: "Customs Hut",
      motion: { kind: "orbit", around: "petty", radius: 1.4, omega: 0.6, phase: 1 },
      captureRadius: 0.4,
    },
    guideSeconds: 4,
    maxFlightSeconds: 8,
    fuelPar: 30,
    bounds: BOUNDS,
    reference: { delayTicks: 180, aim: { angle: 355, power: 40 }, brakeStep: 222 },
  },
  {
    id: "cake",
    title: "The Moon Moves Too",
    client: "Receipt Moon Banqueting",
    item: "Wedding cake (tiered)",
    parcel: "fragile",
    note: "The moon moves. Customer service insists this should not affect delivery.",
    depot: { x: -8, y: -3.5 },
    bodies: [
      {
        id: "ledger",
        name: "Ledger",
        radius: 1.2,
        gm: 6,
        motion: { kind: "fixed", at: { x: 1, y: 0.5 } },
        look: "rust",
      },
      {
        id: "receipt",
        name: "Receipt",
        radius: 0.5,
        gm: 3,
        motion: { kind: "orbit", around: "ledger", radius: 4, omega: 0.2, phase: -2.3 },
        look: "moon",
      },
    ],
    obstacles: [],
    dock: {
      name: "Banqueting Suite",
      motion: { kind: "orbit", around: "receipt", radius: 1.2, omega: 0.6, phase: 0 },
      captureRadius: 0.42,
    },
    guideSeconds: 3.5,
    maxFlightSeconds: 8,
    fuelPar: 60,
    bounds: BOUNDS,
    reference: { delayTicks: 0, aim: { angle: 0, power: 50 }, brakeStep: null },
  },
  {
    id: "anvil",
    title: "Ricochet Authorised",
    client: "Clang & Daughters Forge",
    item: "Anvil (decorative)",
    parcel: "robust",
    note: "Robust parcels may ricochet. Accounts will call this a route.",
    depot: { x: -7, y: -3 },
    bodies: [
      {
        id: "clang",
        name: "Clang",
        radius: 0.7,
        gm: 5,
        motion: { kind: "fixed", at: { x: -4.5, y: 3 } },
        look: "rust",
      },
    ],
    obstacles: [
      { id: "w0", radius: 0.5, motion: { kind: "fixed", at: { x: -9.2, y: 0 } } },
      { id: "w1", radius: 0.5, motion: { kind: "fixed", at: { x: -8.2, y: 0 } } },
      { id: "w2", radius: 0.5, motion: { kind: "fixed", at: { x: -7.2, y: 0 } } },
      { id: "w3", radius: 0.5, motion: { kind: "fixed", at: { x: -6.2, y: 0 } } },
      { id: "w4", radius: 0.5, motion: { kind: "fixed", at: { x: -5.2, y: 0 } } },
      { id: "w5", radius: 0.5, motion: { kind: "fixed", at: { x: -4.2, y: 0 } } },
      { id: "w6", radius: 0.5, motion: { kind: "fixed", at: { x: -3.2, y: 0 } } },
      { id: "bumper", radius: 1, motion: { kind: "fixed", at: { x: 1.5, y: -1 } } },
    ],
    dock: {
      name: "Forge Yard",
      motion: { kind: "orbit", around: "clang", radius: 1.4, omega: -0.5, phase: 3 },
      captureRadius: 0.42,
    },
    guideSeconds: 3.5,
    maxFlightSeconds: 8,
    fuelPar: 70,
    bounds: BOUNDS,
    reference: { delayTicks: 0, aim: { angle: 0, power: 50 }, brakeStep: null },
  },
  {
    id: "complaint",
    title: "Per My Last Transmission",
    client: "Head Office",
    item: "Formal complaint (framed)",
    parcel: "fragile",
    note: "This could have been a wormhole.",
    depot: { x: -8, y: -3.5 },
    bodies: [
      {
        id: "hq",
        name: "Head Office",
        radius: 1.1,
        gm: 10,
        motion: { kind: "fixed", at: { x: -1, y: 0 } },
        look: "gas",
      },
      {
        id: "annex",
        name: "The Annex",
        radius: 0.6,
        gm: 4,
        motion: { kind: "fixed", at: { x: 5, y: 2 } },
        look: "ice",
      },
    ],
    obstacles: [
      {
        id: "r1",
        radius: 0.4,
        motion: { kind: "orbit", around: "hq", radius: 2.6, omega: 0.5, phase: 0 },
      },
      {
        id: "r2",
        radius: 0.4,
        motion: { kind: "orbit", around: "hq", radius: 2.6, omega: 0.5, phase: 2.1 },
      },
      {
        id: "r3",
        radius: 0.4,
        motion: { kind: "orbit", around: "hq", radius: 2.6, omega: 0.5, phase: 4.2 },
      },
    ],
    dock: {
      name: "Complaints Window",
      motion: { kind: "orbit", around: "annex", radius: 1.3, omega: -0.7, phase: 0 },
      captureRadius: 0.4,
    },
    guideSeconds: 3.5,
    maxFlightSeconds: 8,
    fuelPar: 50,
    bounds: BOUNDS,
    reference: { delayTicks: 480, aim: { angle: 11, power: 35 }, brakeStep: 390 },
  },
];
